name: 'Deploy to cPanel Action'
description: 'Deploy a Nuxt.js app to cPanel using custom action'
inputs:
  host:
    description: 'cPanel host'
  username:
    description: 'cPanel username'
  password:
    description: 'cPanel password'
  repository:
    description: 'GitHub repository name'
  branch:
    description: 'GitHub branch name'
  deploy_path:
    description: 'Path to deploy the app on cPanel'

runs:
  using: 'node16'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn

    - name: Build Nuxt.js app
      run: yarn build

    - name: Deploy to cPanel
      run: |
        # Replace the following command with the actual deployment logic
        echo "Deploying to cPanel..."
        echo "Host: ${{ inputs.host }}"
        echo "Username: ${{ inputs.username }}"
        echo "Password: ${{ inputs.password }}"
        echo "Repository: ${{ inputs.repository }}"
        echo "Branch: ${{ inputs.branch }}"
        echo "Deploy Path: ${{ inputs.deploy_path }}"

    - name: Install PM2
      run: npm install pm2 -g

    - name: Start Nuxt.js app with PM2
      run: pm2 start npm --name "your-app-name" -- start
