name: 'My Custom Action'
description: 'A description of your custom action'
author: 'Your Name'
branding:
  icon: 'package'
  color: 'green'

inputs:
  host:
    description: 'The hostname or IP address of the cPanel server'
    required: true
  username:
    description: 'The username for connecting to the cPanel server'
    required: true
  password:
    description: 'The password for the specified username'
    required: true
  repository:
    description: 'The GitHub repository to deploy'
    required: true
  branch:
    description: 'The branch to deploy'
    required: true
  deploy_path:
    description: 'The deployment path on the cPanel server'
    required: true

outputs:
  status:
    description: 'The status of the deployment'

runs:
  using: 'docker'
  image: 'Dockerfile'
