name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: v18.18.2

        - name: Install dependencies
          run: yarn

        - name: Build Nuxt.js app
          run: yarn build

        - name: Deploy to cPanel
          uses: MRaghebdev/CICD@main
          with:
            host: ${{ secrets.CPANEL_HOST }}
            username: ${{ secrets.CPANEL_USERNAME }}
            password: ${{ secrets.CPANEL_PASSWORD }}
            repository: ${{ secrets.GITHUB_REPOSITORY }}
            branch: ${{ github.ref }}
            deploy_path: /public_html # Adjust this path according to your cPanel setup

        - name: Install PM2
          run: npm install pm2 -g

        - name: Start Nuxt.js app with PM2
          run: pm2 start ecosystem.config.cjs
